using UnityEngine;
using System.Collections;
using System.Collections.Generic;

//public enum DBNotificationType
//{
//	DebuggerQuit, // we don't need a class, this is just an event
//    DebuggerError, // needs a class
//    ProgramError, // needs a class
//    ReadLine,     // event
//    Write,        // just a string
//    InteractionBegin // event
//};

namespace DBNotif {

    // for return values which frontend requested through interaction loop
    public class InteractionResult {
        public InteractionResult(string method_, string result_) {
            Result = result_;
            Method = method_;
        }

        public string Result { get; set; }
        public string Method { get; set; }
    }

    public class DBStackTraceElement {
        public override string ToString()
        {
            return string.Format("[{0}:{1}    {2}]", fname, lineno, line.Trim());
        }

        public string fname { get; set; }
        public string lineno { get; set; }
        public string line { get; set; }
    }

    public class DBStackTrace {
        public override string ToString()
        {
            string str = "Stack Trace:";
            foreach (DBStackTraceElement element in trace) {
                str += "\n";
                str += element.ToString();   
            }
            return str;
        }

        public List<DBStackTraceElement> trace { get; set; }
    }

    public class Variable {

        public override string ToString()
        {
            return string.Format("[name={0}, value={1}, type={2}]", name, val, type);
        }

        public string name { get; set; }
        public string val { get; set; }
        public string type { get; set; }
    }

    public class DBEnvironment {
        public override string ToString()
        {
            string locals_str = "===LOCALS===";
            foreach (var variable in locals)
                locals_str += "\n" + variable.ToString();
            string globals_str = "\n===GLOBALS===";
            foreach (var global_ in globals)
                globals_str += "\n" + global_.ToString();
            return "Environment:\n" + locals_str + globals_str;
        }

        public List<Variable> locals { get; set; }
        public List<Variable> globals { get; set; }
    }

    public class InteractionArgs {
        public InteractionArgs(string filename_, string lineno_, string line_) {
            this.filename = filename_;
            this.lineno = lineno_;
            this.line = line_;
        }

        public override string ToString()
        {
            return string.Format("{0} ({1}) => {2}", filename, lineno, line);
        }

        public string filename { get; set; }
        public string lineno { get; set; }
        public string line { get; set; }
    }

    public class DebuggerError {
        public DebuggerError(string code_, string message_) {
            this.code = code;
            this.message = message_;
        }

        public override string ToString() // autogenerated by Visual Studio :D
        {
            return string.Format("[DebuggerError: code={0}, message={1}]", code, message);
        }

        public string code {get;set;}
        public string message {get;set;}
    }

    public class ProgramError {
        public ProgramError(string title_, string type_, string val_, string trace_, string message_) {
            this.title = title_;
            this.type = type_;
            this.val = val_;
            this.trace = trace_;
            this.message = message_;
        }

        public override string ToString()
        {
            return string.Format("[ProgramError: title={0}, type={1}, val={2}, trace={3}, message={4}]", title, type, val, trace, message);
        }

        public string title {get;set;}
        public string type {get;set;}
        public string val {get;set;}
        public string trace {get;set;}
        public string message {get;set;}
    }
}
